- name: Hello World Sample
  hosts: all
  vars:
    pause: 5
    loop: 25
  tasks:
  - name: "Pause {{ pause }} minutes"
    include_tasks: pause-task.yml
    loop: "{{ query('sequence', 'start=1 end={{loop}}') }}"
