- name: Hello World Sample
  hosts: all
  vars:
    pause: 4
    loop_count: 100
  tasks:
  - name: "Pause {{ pause }} seconds"
    include_tasks: pause-task.yml
    loop: "{{ query('sequence', 'start=1 end={{ loop_count }}') }}"
